CC = gcc
CFLAGS = -Wall

all:	program1 program2

program1:   star.c
	$(CC) $(CFLAGS) -o program1 star.c
    
program2:   fibonacci.c
	$(CC) $(CFLAGS) -o program2 fibonacci.c


clean:
	rm -f program1 program2